### PR TITLE
Created a basic README.md

### PR DESCRIPTION
**Pull request by tarasivashchuk**
Contains a basic overview of the project's functionality, as well as links to the original author's GitHub page and the corresponding blog post from "towardsdatascience.com"

### CODE REVIEW

**Comment by tarasivashchuk** [comment]
Let me know if there's anything that should be changed or added. Thanks!

**Comment by khuyentran1401** [comment]
Hey Taras,

Thank you for creating a nice README.md. I enjoy reading your description
of the project and the link to my article. About your offer of
collaboration, there are 4 parts of this project I am working on:
-Developing ideas
-Developing mathematical formulations
-Creating a basic app
-Adding more personalized features using machine learning.

You can find the description of this project through the PDF I sent. Let me
know what you think and which part you are interested in helping me with.
Any help from you would be greatly appreciated.

Thank you,
Khuyen Tran

**Comment by tarasivashchuk** [comment]
I didn’t receive a PDF? Or I’m not sure where to look - which is just as likely lol




Taras Ivashchuk

Machine Learning Engineer

Email:  taras@tarasivashchuk.com

Cell:   +1 (330) 252-7361



Web:    https://tarasivashchuk.com

**Comment by khuyentran1401** [comment]
Hey Taras, it is a Word doc. Did you receive any? I could resend in pdf
instead

**Comment by khuyentran1401** [comment]
This is the pdf proposal of the project. Let me know if you received it

**Pull request merged**
